---
- name: install and prep mongodb
  hosts: mongodb_host
  become: True
  gather_facts: True
  tags:
      - onadata
  tasks:

    - name: Add preferred mongodb repo
      apt_repository:
        repo: deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen
        state: present

    - name: Trust the preferred mongodb repo
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 7F0CEB10
        state: present

    - name: Update cache before install, just for good measure
      apt:
        update_cache: yes

    - name: Install mongodb
      apt:
        pkg: "{{ item }}"
        state: latest
        update_cache: yes
        cache_valid_time: 600
      with_items:
        - mongodb-org
